################################################################################
## Input file descriptions
################################################################################

# Config parameters in this file are used as defaults by the pipeline (Snakefile).
# To override the defaults, create a copy of this file and pass your new file to snakemake using the --configfile flag.
# Any parameters in the new config file will overwrite the defaults listed here.

###########
# File IO #
###########

# Specify the input and output directories
input_dir: "inputs/"
output_dir: "outputs/demo_protein"
orfs_amino_acids: "demo/orfs_amino_acids.faa"
